### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by jaaso** [solidgear/collaborative-newsletter#3]
Got this error when I try to login. 

```TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at Object.randomBytes (internal/crypto/random.js:44:11)
    at Object.options.source (/Users/jrahimic/Downloads/collaborative-newsletter-master/backend/node_modules/rand-token/index.js:60:25)
    at Object.generate (/Users/jrahimic/Downloads/collaborative-newsletter-master/backend/node_modules/rand-token/index.js:95:29)
    at exports.createRefreshToken (/Users/jrahimic/Downloads/collaborative-newsletter-master/backend/domain/auth/refreshTokens.js:42:40)
    at getRefreshTokenByUserId.then.refreshToken (/Users/jrahimic/Downloads/collaborative-newsletter-master/backend/domain/auth/refreshTokens.js:23:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)```

**Comment by davicente** [comment]
hi @jaaso, what version of node are you using?

**Comment by jaaso** [comment]
It is v9.5.0.

**Comment by davicente** [comment]
We currently support LTS version (currently is v8.10.0).
I found an issue in the libray rand-token that can fix it: 
https://github.com/sehrope/node-rand-token/issues/9

Apparently you only have to update library rand-token to version 0.4.0

Let us know if it worked

**Comment by jaaso** [comment]
It's working now. 
Thanks.
